-- TABLE POSTALCODE

INSERT INTO POSTALCODE(POSTALCODE_ID, POSTALCODE, POSTALCODE_LABEL)
VALUES (nextval('postalcode_seq'), '1000', 'Bruxelles');
INSERT INTO POSTALCODE(POSTALCODE_ID, POSTALCODE, POSTALCODE_LABEL)
VALUES (nextval('postalcode_seq'), '1030', 'Schaarbeek');
INSERT INTO POSTALCODE(POSTALCODE_ID, POSTALCODE, POSTALCODE_LABEL)
VALUES (nextval('postalcode_seq'), '1050', 'Ixelles');

-- TABLE ADDRESSES

INSERT INTO ADDRESSES(ADDRESS_ID, STREET_NAME, STREET_NUMBER, POSTALCODE_ID)
VALUES (nextval('addresses_seq'), 'Boulevard Anspach', '5', '1');

-- TABLE PERSON_DETAILS

INSERT INTO PERSON_DETAILS(PERSON_DETAILS_ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESS_ID, MOBILE_PHONE)
VALUES (nextval('person_details_seq'), 'Peter', 'Parker', 'peter.parker@gmail.com', 1, 0032487545856);