--Insert into PERSONS (PERSON_ID,FAVORITE_COLOR,FIRST_NAME,LAST_NAME) values ('1','Yellow','Renaud','Berthet');
--Insert into PERSONS (PERSON_ID,FAVORITE_COLOR,FIRST_NAME,LAST_NAME) values ('2','CovFefe','Donald','Trump');
--Insert into PERSONS (PERSON_ID,FAVORITE_COLOR,FIRST_NAME,LAST_NAME) values ('3','Brown','Manfred','TheePot');
--Insert into PERSONS (PERSON_ID,FAVORITE_COLOR,FIRST_NAME,LAST_NAME) values ('4','Red','Indiana','Poulos');
--Insert into PERSONS (PERSON_ID,FAVORITE_COLOR,FIRST_NAME,LAST_NAME) values ('5','Blue','Thuyr','Karbur');
--Insert into PERSONS (PERSON_ID,FAVORITE_COLOR,FIRST_NAME,LAST_NAME) values ('6','Cyan','John','Lee');