CREATE TABLE PERSONS
   (	"PERSON_ID" NUMBER(19,0) NOT NULL,
	"FAVORITE_COLOR" VARCHAR2(255 CHAR),
	"FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL,
	"LAST_NAME" VARCHAR2(255 CHAR) NOT NULL
   );
ALTER TABLE PERSONS ADD PRIMARY KEY ("PERSON_ID");

CREATE SEQUENCE IF NOT EXISTS DIVISIONS_SEQ START WITH 1 increment by 1 no cycle no cache;
