-- TABLE POSTALCODE

CREATE TABLE POSTALCODE
   (	"POSTALCODE_ID" NUMBER(6,0) NOT NULL,
	    "POSTALCODE" VARCHAR2(10 CHAR) NOT NULL,
	    "POSTALCODE_LABEL" VARCHAR2(255 CHAR) NOT NULL
   );
ALTER TABLE POSTALCODE ADD PRIMARY KEY ("POSTALCODE_ID");

CREATE SEQUENCE IF NOT EXISTS POSTALCODE_SEQ START WITH 1 increment by 1 no cycle no cache;

-- TABLE ADDRESSES

CREATE TABLE ADDRESSES
   (	"ADDRESS_ID" NUMBER(6,0) NOT NULL,
	    "STREET_NAME" VARCHAR2(255 CHAR) NOT NULL,
	    "STREET_NUMBER" VARCHAR2(5 CHAR),
        "POSTALCODE_ID" NUMBER(6,0)
   );
ALTER TABLE ADDRESSES ADD PRIMARY KEY ("ADDRESS_ID");
ALTER TABLE ADDRESSES ADD FOREIGN KEY ("POSTALCODE_ID") REFERENCES POSTALCODE(POSTALCODE_ID);

CREATE SEQUENCE IF NOT EXISTS ADDRESSES_SEQ START WITH 1 increment by 1 no cycle no cache;

-- TABLE PERSON_DETAILS

CREATE TABLE PERSON_DETAILS
   (	"PERSON_DETAILS_ID" NUMBER(6,0) NOT NULL,
	    "FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL,
	    "LAST_NAME" VARCHAR2(255 CHAR) NOT NULL,
	    "EMAIL" VARCHAR2(255 CHAR) NOT NULL,
	    "ADDRESS_ID" NUMBER(6,0) NOT NULL,
	    "MOBILE_PHONE" VARCHAR2(20 char),
	    "FIXED_PHONE" VARCHAR2(20 char)
   );
ALTER TABLE PERSON_DETAILS ADD PRIMARY KEY ("PERSON_DETAILS_ID");
ALTER TABLE PERSON_DETAILS ADD FOREIGN KEY ("ADDRESS_ID") REFERENCES ADDRESSES(ADDRESS_ID);

CREATE SEQUENCE IF NOT EXISTS PERSON_DETAILS_SEQ START WITH 1 increment by 1 no cycle no cache;

-- TABLE DIVISIONS

CREATE TABLE DIVISIONS
   (	"DIVISION_ID" NUMBER(6,0) NOT NULL,
	    "DIVISION_NAME" VARCHAR2(255 CHAR) NOT NULL,
	    "ORIGINAL_NAME" VARCHAR2(255 CHAR) NOT NULL,
	    "DIRECTOR" VARCHAR2(255 CHAR) NOT NULL,
	    "PARENT_DIVISION_ID" NUMBER(6,0)
   );
ALTER TABLE DIVISIONS ADD PRIMARY KEY ("DIVISION_ID");
ALTER TABLE DIVISIONS ADD FOREIGN KEY ("PARENT_DIVISION_ID") REFERENCES DIVISIONS(DIVISION_ID);
ALTER TABLE DIVISIONS ADD UNIQUE("DIVISION_NAME");

CREATE SEQUENCE IF NOT EXISTS DIVISIONS_SEQ START WITH 1 increment by 1 no cycle no cache;

-- TABLE MEMBERS

CREATE TABLE MEMBERS
    (   "MEMBER_ID" NUMBER(6,0) NOT NULL,
        "PERSON_DETAILS_ID" NUMBER(6,0) NOT NULL,
        "LICENSE_PLATE_NUMBER" VARCHAR2 (9 CHAR) NOT NULL,
        "ISSUING_COUNTRY" VARCHAR2 (255 CHAR) NOT NULL,
        "REGISTRATION_DATE" DATE NOT NULL
    );

ALTER TABLE MEMBERS ADD PRIMARY KEY ("MEMBER_ID");
ALTER TABLE MEMBERS ADD FOREIGN KEY ("PERSON_DETAILS_ID") REFERENCES PERSON_DETAILS(PERSON_DETAILS_ID);

CREATE SEQUENCE IF NOT EXISTS MEMBERS_SEQ START WITH 1 increment by 1 no cycle no cache;